### ISSUE TITLE
Mauvais téléchargement

### ISSUE THREAD

**Issue by mpo-deltacode** [sgmap/sirene_as_api_ansible#10]
Bonjour, je post ma demande sur ce repository, n'ayant pas eu de reponse sur celui de l'API

Je viens de remarquer que Sirene voit bien le fichier d'Aout 2019 comme étant le dernier en date, mais il telecharge le fichier de Juillet 2019, et il y a une erreur dans le fichier, d'après le retour de la console
![Screenshot 2019-08-26 at 13 42 02](https://user-images.githubusercontent.com/49921482/63833999-9124ad00-c974-11e9-8f17-6a70ce1dc96c.png)

Autre chose que je viens de remarquer également. La version de SmarterCSV fait planter le peuplement de la base
![Screenshot 2019-08-27 at 10 04 24](https://user-images.githubusercontent.com/49921482/63834028-9eda3280-c974-11e9-8767-9daee2657c3a.png)

Cordialement

**Comment by Samuelfaure** [comment]
Bonjour

Je reprend votre question sur l'autre repo.
